spring:
  application:
    name: ecommerce-batch


  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: postgres
    password: testpassword
    hikari:
      maximum-pool-size: 200


  batch:
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true


logging:
  level:
    root: info
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG

prometheus:
  job:
    name: spring-batch
  pushgateway:
    url: localhost:9091
